adamhundley/the_pivot

db/migrate/20160322204950_create_properties.rb, db/schema.rb, readme.md
Hey dudes. I added the property table to the database. 
@natevenn @Salvi6God
=> Create property db

readme.md
A better edited ReadMe that reflects the current state of CAMP rather than
keeping the same ReadMe from Little Owl. This ReadMe includes two gifs that
reflect the "before pivot" user interface for both admin and a regular user.
This will be updated later on once CAMP is finished.
closes #8
=> Edit ReadMe

db/seeds.rb
change property type to create only 3 objects
add method to create relationship to property
closes#29
=> change generate property type

db/seeds.rb
add second method to create association with amenities and properties
closes#28
closes#32
=> add method to generate amenities

app/assets/stylesheets/orders.scss, app/views/sessions/_login_form.html.erb, app/views/sessions/new.html.erb, app/views/shared/_current_user.html.erb, app/views/users/new.html.erb
user drop down now shows my dashboard instead of orders
list my pad now correctly links to new_user_property_path
closes#30
=> User drop down#27

config/routes.rb, db/migrate/20160324225152_rename_table_orders_to_reservations.rb, db/migrate/20160324225738_add_column_property_id_to_reservations.rb, db/migrate/20160324233718_add_column_check_in_check_out_to_reservations.rb, db/schema.rb
changed name of orders table to reservation and added three more columns checkin, checkout, and property id
added path index and show to property and then deleted. will add it later
closes#44
=> Create reservation table

app/controllers/user/properties_controller.rb, app/models/property_amenitizer.rb, app/views/shared/_user_dashboard_header.html.erb, app/views/user/properties/index.html.erb, app/views/user/properties/new.html.erb, app/views/users/show.html.erb, config/routes.rb, db/schema.rb, spec/factories.rb, spec/features/user/user_lists_their_property_spec.rb, spec/features/user/user_views_their_approved_property_in_dashboard_spec.rb, spec/mailers/order_mailer_spec.rb, spec/models/comment_spec.rb, spec/models/order_processor_spec.rb, spec/models/order_product_spec.rb, spec/models/order_spec.rb, spec/models/property_amenitizer_spec.rb, spec/spec_helper.rb
User property index page
* user can view approved properties
* styled a user viewing their properties
* Property amenitizer PORO created to assign amenity object to properties
* adjusted user dashboard navbar
* need to implement update action
* need to implement destroy action
* many other small things
=> Approved property in dashboard#37

app/controllers/sessions_controller.rb, app/helpers/user_helper.rb, app/views/shared/_current_user.html.erb, app/views/user/properties/new.html.erb, config/environments/development.rb, spec/features/user/non_logged_in_users_need_to_login_before_listing_properties_spec.rb, spec/features/user/user_lists_their_property_spec.rb, xml-schema.xml
They will be redirected to the login page if they try to access
certain functionalities of the website. Once they are done logging-in,
they will be redirected to the dashboard where they will be greeted with a
flash message.
closes#50
=> Guest Will Be Redirected to Login

app/controllers/user/properties_controller.rb, app/views/shared/_no_listings.html.erb, app/views/user/properties/index.html.erb, spec/features/user/user_without_listing_clicks_on_my_listings_spec.rb
* a user now sees the opportunity to post a listing when they click on my listings in the dashboard
* page could still use some styling
* wrote feature test as well
closes#51
=> user with no listings

app/models/property.rb, app/models/reservation.rb, app/models/reservation_night.rb, app/models/reservation_night_calculator.rb, app/models/user.rb, db/migrate/20160326171050_create_reservation_nights.rb, db/schema.rb, spec/factories.rb, spec/models/reservation_night_calculator_spec.rb, spec/models/reservation_night_spec.rb, spec/models/reservation_spec.rb
@Salvi6God @adamhundley 
look over the reservation night calculator class and let me know if I can do any refactoring in the PORO
=> Create reservation nights table and associations

app/models/reservation_night.rb, db/seeds.rb, spec/models/reservation_night_spec.rb
generate association b/w reservation-user-and-properties
create reservation_nights based off of reservation checkin and checkout dates
closes#63
=> seed reservations and reservation nights

db/seeds.rb
add four images of interior house and create relationship with property
closes#68
=> seed data with four images from aws

app/assets/stylesheets/properties.scss, app/controllers/properties_controller.rb, app/views/properties/index.html.erb, app/views/user/properties/show.html.erb, spec/features/user/user_view_a_specific_propreties_show_page_spec.rb, spec/features/user/user_views_properties_for_a_location_spec.rb, spec/spec_helper.rb
* property index complete
* added test
* styled index and adjusted show style
* added clause for if someone goes to /properties or searches a city that doesn't exist, the search bar doesn't show up
closes#76
=> property index

app/views/shared/_searchbar.html.erb, config/database.yml
used html5 require in order to not let a user search without filling those in
=> added requiring for city, state and checkin/out dates

app/assets/stylesheets/home.scss, app/views/home/index.html.erb, app/views/shared/_checkout_form.html.erb, config/routes.rb
search bar is now fully in the hero image
=> fixed searchbar position

app/assets/stylesheets/home.scss, app/controllers/properties_controller.rb, app/helpers/properties_helper.rb, app/views/home/index.html.erb, app/views/layouts/application.html.erb, app/views/properties/new.html.erb, app/views/shared/_city_imgs.html.erb, app/views/shared/_searchbar_properties.html.erb
add link tag to featured cities and display on properties index
refactor index controller and add helper methods for geo info, geo location, and find_city
add helper methods for property index with conditionals that help to set the placeholders for the searchbar
=> Link major city images to property index

app/controllers/user/properties_controller.rb, app/helpers/properties_helper.rb, app/models/property.rb, app/views/properties/index.html.erb
* now grabs prices from the page
* properties now sorted by price
=> Price slider

app/views/shared/_current_user.html.erb, spec/features/user/non_logged_in_users_need_to_login_before_listing_properties_spec.rb
change redirect_path to user dashboard
=> fix non-logged in user feature test

app/controllers/properties_controller.rb, app/models/property.rb, app/views/properties/index.html.erb, app/views/shared/_searchbar.html.erb, app/views/shared/_searchbar_properties.html.erb
changed some logic for properties controller
also fixed issue where map wasn't displaying in certain cases
=> refactor properties controller

app/assets/stylesheets/home.scss, app/assets/stylesheets/properties.scss, app/assets/stylesheets/shared.scss, app/controllers/properties_controller.rb, app/models/property.rb, app/views/home/index.html.erb, app/views/shared/_city_imgs.html.erb, app/views/shared/_mailing_list.html.erb
finished some home page styling
took out "featured cities"
widened calendar openings
moved mailer up
=> Home page styling

Gemfile, Gemfile.lock
=> added brakeman to gemfile and ran

app/assets/javascripts/admin/image_form_cover.js, app/controllers/sessions_controller.rb, app/controllers/user/properties_controller.rb, app/models/property.rb, app/views/shared/_search_map.html.erb, app/views/user/properties/index.html.erb, spec/mailers/order_mailer_spec.rb
=> Add multiple images#59

Gemfile, Gemfile.lock, app/controllers/admin/users_controller.rb, app/models/reservation.rb, app/models/user.rb, app/views/admin/users/show.html.erb, config/routes.rb, db/seeds.rb, spec/features/admin/platform_admins_dashboad_displays_data_spec.rb
On dashboard, Platform Admin can now has a visual representation of all of the
revenue the website has created and stats about the cities and states of where
these checkin's have/will occur.
closes#133
check it! @adamhundley @natevenn
=> Platform Admin's Dashboard Displays Data

app/controllers/properties_controller.rb, app/models/property.rb, app/views/properties/index.html.erb, app/views/shared/_search_map.html.erb, db/seeds.rb, spec/factories.rb, spec/features/admin/platform_admin_approves_a_listing_spec.rb, spec/features/admin/platform_admin_can_disable_properties_spec.rb, spec/features/admin/platform_admin_can_view_individual_properties_spec.rb, spec/features/user/user_books_a_property_spec.rb
we now scope to only active status'
fixed some conflicts
=> Scope to status

app/controllers/user/properties_controller.rb, app/views/shared/_search_map.html.erb, config/initializers/geocoder.rb, db/seeds.rb, spec/models/user_spec.rb
=> Final adjustments
